version: "3.9"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: k304298
    volumes:
      - local_pgdata:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./local_pgdata/data/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@kku.ac.th
  #     PGADMIN_DEFAULT_PASSWORD: k304298
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  web:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=uvolt360.kku.ac.th
    - NGINX_PORT=80
  webapp:
    container_name: uvolt
    restart: always
    build: backend/.
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  local_pgdata:
  # pgadmin-data: