POST http://<hostname>/users
Content-Type: application/json
{
    "id": 125,
    "date": "20/08/66",
    "time": "20:00:00",
    "voltage": 70.01,
    "current": 0.01,
    "Cell": [
      3.01, 3.02, 3.03, 3.04, 3.05, 3.06, 3.07, 3.08, 3.09, 3.1, 3.11, 3.12,
      3.13, 3.14, 3.15, 3.16, 3.17, 3.18
    ],
    "avg cell": 3.09,
    "max_cell": 3.18,
    "min_cell": 3.01,
    "SOC": 98,
    "remaincap": 13220,
    "fcc": 2500,
    "cycle": 2,
    "temp": [25.1, 25.2, 25.3, 25.4],
    "ProtectStatus": 0,
    "BalanceStatus": 0,

    "lon": 100.56,
    "lat": 13.74
  
}

###

GET http://127.0.0.1:8000/a/2
###
GET https://long-places-cry.loca.lt